// Builds the per-project llms.txt that the client publishes at the root of
// their own domain (https://their-site/llms.txt). It's a markdown summary of
// what the site is about, what it sells, how it's structured, and the
// top topics it covers — designed so an LLM crawler can orient itself in
// one fetch instead of crawling the whole site.
//
// Source data (CompanyProfile + SemanticCore + SitemapPage) is gathered from
// what onboarding + later steps have already populated. Sections that have
// no data are silently skipped so the file stays compact for fresh projects.

import { prisma } from "../../db";

type ProductsServices = Array<{ name?: string; description?: string; priceRange?: string }>;
type SiteStructureNode = { name?: string; url?: string; children?: SiteStructureNode[] };

export async function buildLlmsTxt(projectId: string): Promise<string> {
  const project = await prisma.project.findUnique({
    where: { id: projectId },
    include: {
      companyProfile: true,
      sitemapPages: { take: 30, orderBy: { url: "asc" } },
      semanticCores: {
        orderBy: { updatedAt: "desc" },
        take: 1,
        include: {
          queries: {
            take: 100,
            orderBy: { usageCount: "desc" },
            include: { category: { select: { name: true } } },
          },
        },
      },
    },
  });

  if (!project) throw new Error(`Project not found: ${projectId}`);

  const cp = project.companyProfile;
  const name = cp?.companyName || project.name;
  const lines: string[] = [];

  lines.push(`# ${name}`);
  lines.push("");

  const tagline = buildTagline(cp, project.url);
  if (tagline) {
    lines.push(`> ${tagline}`);
    lines.push("");
  }

  // ── Products & Services ──
  const products = (cp?.productsServices as ProductsServices | null) ?? [];
  const validProducts = products.filter(p => p?.name);
  if (validProducts.length > 0) {
    lines.push("## Products & Services");
    lines.push("");
    for (const p of validProducts) {
      const desc = [p.description, p.priceRange].filter(Boolean).join(" — ");
      lines.push(desc ? `- **${p.name}**: ${desc}` : `- **${p.name}**`);
    }
    lines.push("");
  }

  // ── Site Structure ──
  // Merge approved siteStructure tree (from onboarding) with discovered sitemap
  // pages. Prefer structure entries since they have curated names; fall back
  // to raw URLs.
  const structureLines = flattenStructure(cp?.siteStructure as SiteStructureNode | null);
  const sitemapLines = project.sitemapPages
    .filter(p => p.url)
    .map(p => `- [${p.title || p.h1 || p.url}](${p.url})`);
  const allStructure = [...structureLines, ...sitemapLines];
  if (allStructure.length > 0) {
    lines.push("## Site Structure");
    lines.push("");
    // De-dupe by trailing URL
    const seen = new Set<string>();
    for (const line of allStructure) {
      const key = line.match(/\(([^)]+)\)/)?.[1] ?? line;
      if (seen.has(key)) continue;
      seen.add(key);
      lines.push(line);
    }
    lines.push("");
  }

  // ── Key Topics (top 20 queries grouped by category) ──
  const core = project.semanticCores[0];
  if (core && core.queries.length > 0) {
    const byCategory = new Map<string, string[]>();
    for (const q of core.queries) {
      const cat = q.category?.name || "Other";
      if (!byCategory.has(cat)) byCategory.set(cat, []);
      const bucket = byCategory.get(cat)!;
      if (bucket.length < 8) bucket.push(q.text); // cap per-category to stay readable
    }
    if (byCategory.size > 0) {
      lines.push("## Key Topics");
      lines.push("");
      lines.push("> Search queries this site targets, grouped by topic.");
      lines.push("");
      for (const [cat, queries] of byCategory) {
        lines.push(`### ${cat}`);
        lines.push("");
        for (const q of queries) lines.push(`- ${q}`);
        lines.push("");
      }
    }
  }

  // ── Trailing meta ──
  lines.push("---");
  lines.push("");
  lines.push(`*Generated by [SEOSH.AI](https://seosh.aijam.pro) on ${new Date().toISOString().slice(0, 10)}.*`);
  lines.push("");

  return lines.join("\n");
}

function buildTagline(cp: { description: string | null; usp: string | null; industry: string | null; geography: string | null } | null, url: string | null): string {
  if (!cp) return url ? `Website: ${url}` : "";
  const bits: string[] = [];
  if (cp.description) bits.push(cp.description.trim());
  if (cp.usp) bits.push(cp.usp.trim());
  const meta = [cp.industry, cp.geography].filter(Boolean).join(", ");
  if (meta && bits.length === 0) bits.push(meta);
  return bits.join(" ");
}

function flattenStructure(node: SiteStructureNode | null, prefix = ""): string[] {
  if (!node || typeof node !== "object") return [];
  const children = Array.isArray(node.children) ? node.children : [];
  const out: string[] = [];
  for (const child of children) {
    if (!child?.name) continue;
    const label = child.url ? `[${child.name}](${child.url})` : child.name;
    out.push(`${prefix}- ${label}`);
    if (child.children?.length) {
      out.push(...flattenStructure(child, prefix + "  "));
    }
  }
  return out;
}

/** Generate and persist llms.txt for a project. Returns the new text. */
export async function regenerateProjectLlmsTxt(projectId: string): Promise<string> {
  const text = await buildLlmsTxt(projectId);
  await prisma.project.update({
    where: { id: projectId },
    data: { llmsTxt: text, llmsTxtUpdatedAt: new Date() },
  });
  return text;
}
